### ISSUE TITLE
v0.1.0

### ISSUE THREAD

**Issue by zhuangsuph** [carson-katri/dream-textures#571] opened 2023-02-17 15:06 UTC
Installation prompt error
Traceback (most recent call last):
  File "F:\Program Files\blender-3.2.0-alpha\3.2\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\dream_textures\__init__.py", line 40, in <module>
    from .prompt_engineering import *
ModuleNotFoundError: No module named 'dream_textures.prompt_engineering'

**Comment by carson-katri** [comment] 2023-02-17 15:12
Duplicate of #464

**Closed by carson-katri** 2023-02-17 15:12 UTC
