### ISSUE TITLE
I dont make to install the dependencies

### ISSUE THREAD

**Issue by Kalamiardo** [carson-katri/dream-textures#52] opened 2022-09-21 19:37 UTC
When i click install it starts (i think) and after 5-6 seconds appears an error saying this: ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: C:\Users\username\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream-textures-main\stable_diffusion
WARNING: You are using pip version 21.2.4; however, version 22.2.2 is available.
You should consider upgrading via the 'C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\bin\python.EXE -m pip install --upgrade pip' command.
i have tried to unzip the python zip that appears in  C:\Users\username\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream-textures-main into the adress C:\Users\username\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream-textures-main\stable_diffusion 
but didnt work it just appeared another error i have reinstalled it so for run it for clean
I dont know about coding much 
also apologies for my english (not first language)

**Comment by carson-katri** [comment] 2022-09-21 19:37
This a duplicate of #47

**Closed by carson-katri** 2022-09-21 19:37 UTC
