### ISSUE TITLE
No module named 'dream_textures.prompt_engineering'

### ISSUE THREAD

**Issue by ShrimpyChips** [carson-katri/dream-textures#605] opened 2023-03-21 00:53 UTC
### Description

I've tried installing both from the latest (v0.1.0) on github and from the one on Blender Market and with both I'm getting the same error:

No module named 'dream_textures.prompt_engineering'

I've tried running blender as admin as well and I get the same error.

### Steps to Reproduce

1) Install the script via the zip file.
2) Check the box to turn on the addon
3) Get the error

### Expected Behavior

Not get an error?

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by Naayi** [comment] 2023-03-23 14:07
Same problem
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\__init__.py", line 40, in <module>
    from .prompt_engineering import *
ModuleNotFoundError: No module named 'dream_textures.prompt_engineering'

**Comment by ShrimpyChips** [comment] 2023-03-23 18:11
Just an update to this. This issue exists on my windows 10 box but I later tried installing it on my windows 11 box and had no issues. Not sure that's related. I've also done a clean install of Blender on the windows 10 box and I'm still getting the same issue.

**Comment by carson-katri** [comment] 2023-03-25 17:33
Duplicate of #464

**Closed by carson-katri** 2023-03-25 17:33 UTC
Labels: bug
