### ISSUE TITLE
File "setup.py" or "setup.cfg" not found

### ISSUE THREAD

**Issue by ortizgab** [carson-katri/dream-textures#121] opened 2022-09-25 01:40 UTC
ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: C:\Users\go_gr\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream-textures-main\stable_diffusion

Any ideas?

**Comment by ortizgab** [comment] 2022-09-25 01:40
also:

WARNING: You are using pip version 21.2.4; however, version 22.2.2 is available.
You should consider upgrading via the 'C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\bin\python.EXE -m pip install --upgrade pip' command.

**Comment by Voyager137** [comment] 2022-09-25 04:15
You have to download the addon from the releases tab:
https://github.com/carson-katri/dream-textures/tags

**Comment by ortizgab** [comment] 2022-09-25 06:03
I'm getting these errors when installing dependencies...

**Comment by carson-katri** [comment] 2022-09-25 13:08
Closing as a duplicate of #47

**Closed by carson-katri** 2022-09-25 13:08 UTC
