### ISSUE TITLE
Generates a green image

### ISSUE THREAD

**Issue by Njenjo** [carson-katri/dream-textures#313] opened 2022-10-14 23:34 UTC
**Is this a known issue?**
I don't know if it's known because I can't find it anywhere.

**Describe the bug**
Prompt was "wood texture", resolution 512x512, precision was float16, seamless was enabled and everything else on default but the generated image was completely green.

**To Reproduce**
1. Set prompt to "texture"
2. Set the subject to "wood"
3. Enable seamless
4. Set precision to "Half precision(float16)"
5. See green image

**Expected behavior**
I thought the AI would generate an image of wood.

**Screenshots**
![GreenImage](https://user-images.githubusercontent.com/115847042/195957704-82435663-195c-4ab7-9d20-86587768e628.png)

**System (please complete the following information):**
- OS
  - [x] Windows
  - [ ] macOS
  - [ ] Other
- GPU
  - [x] NVIDIA
  - [ ] NVIDIA 16*XX*
  - [ ] Apple Silicon
  - [ ] AMD
- Addon Version
  - Latest

**Additional context**
Nothing to add.

**Comment by carson-katri** [comment] 2022-10-14 23:50
Duplicate of #308

**Closed by carson-katri** 2022-10-14 23:50 UTC
Labels: bug
