### ISSUE TITLE
Getting error on installing dependencies

### ISSUE THREAD

**Issue by Wolfy0329** [carson-katri/dream-textures#115] opened 2022-09-24 11:39 UTC
ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/Users/ray/Library/Application Support/Blender/3.3/scripts/addons/dream-textures-main/stable_diffusion/requirements-mac-MPS-CPU.txt'
And I got no idea how to sort this out

**Comment by carson-katri** [comment] 2022-09-24 12:30
Closing as a duplicate of #87

**Closed by carson-katri** 2022-09-24 12:30 UTC
