### ISSUE TITLE
Support for using Automatic1111!

### ISSUE THREAD

**Issue by Ainaemaet** [carson-katri/dream-textures#597] opened 2023-03-10 22:53 UTC
Hello, You'll be happy to give us that as I started using this plugin a couple months ago and have to say it's the best blender plugin out there, with the only exception really being that other plugins allow you to use your own backend, like Automatic1111 - and having to install yet another stable diffusion backend is frustrating when many of us already have one that works really well. 

It would also allow those of us who use Automatic1111 to easily move back and forth between the two for special use and iteration, without having to close down one and open up the other in order to save VRAM. 

Thank you so much, I
Anyhow, apologies for making another post about this but I'm fairly new to Github still and unsure whether or not it's like a 'bump' or if if it's taboo; but I really want to express the desire I see people having for this feature as it would make this hands down the absolute coolest plugin for Blender in existence.

**Comment by carson-katri** [comment] 2023-03-10 23:20
Duplicate of #572

**Closed by carson-katri** 2023-03-10 23:20 UTC
Labels: enhancement
