### ISSUE TITLE
Unable to use any of the versions (blender3.2)

### ISSUE THREAD

**Issue by ninebluestudio** [carson-katri/dream-textures#564] opened 2023-02-12 17:31 UTC
### Description

Unable to use any of the versions(blender3.2)
![a](https://user-images.githubusercontent.com/7386143/218326885-1613b981-a907-4078-b3d5-843c84ad31ea.jpg)
![b](https://user-images.githubusercontent.com/7386143/218326900-c5c0fe8e-f0b4-4cd6-bfd1-8ce2ffc624c7.jpg)
![c](https://user-images.githubusercontent.com/7386143/218326908-7298b141-66c9-4740-800d-8002b3338f7f.jpg)

### Steps to Reproduce

Just install

### Expected Behavior

Ability to use it

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by carson-katri** [comment] 2023-02-12 17:36
Duplicate of #372

**Closed by carson-katri** 2023-02-12 17:36 UTC
Labels: bug
