### ISSUE TITLE
0.0.9 image upscaler not working :(

### ISSUE THREAD

**Issue by HyperStudio-2020** [carson-katri/dream-textures#478] opened 2022-12-25 17:36 UTC
### Description

I get this error: 

Fetching 14 files: 100%|█████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 3493.17it/s]
Exception: Traceback (most recent call last):
  File "C:\Users\th\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actor.py", line 273, in _receive
    for res in iter(response):
  File "C:\Users\th\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actions\upscale.py", line 52, in upscale
    low_res_image = Image.fromarray(image)
  File "C:\Users\th\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\PIL\Image.py", line 2982, in fromarray
    arr = obj.__array_interface__
AttributeError: 'str' object has no attribute '__array_interface__'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\th\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actor.py", line 111, in run_callbacks
    done_callback(self)
  File "C:\Users\th\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\operators\upscale.py", line 114, in image_done
    tile: ImageUpscaleResult = future.result()
  File "C:\Users\th\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actor.py", line 58, in result
    raise self._exception
AttributeError: 'str' object has no attribute '__array_interface__'

### Steps to Reproduce

1. Enable 0.0.9 add-on
2. Follow the steps in the add-on Dream textures window in the preferences
3. Generate an image with the add-on 
4. Click on Upscale to 2048x2048

### Expected Behavior

Get an upscaled version of the image

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by JasonHoku** [comment] 2022-12-25 23:35
Possible duplicate of #432

**Closed** 2023-01-15 13:45 UTC
Labels: bug
