### ISSUE TITLE
macOS Bake to UV failed

### ISSUE THREAD

**Issue by enzyme69** [carson-katri/dream-textures#590] opened 2023-03-07 01:07 UTC
### Description

I cannot get this "bake" feature to work properly. I think I could get better result manually doing it. 

https://github.com/carson-katri/dream-textures/pull/495

### Steps to Reproduce

Try doing the bake, point into the UV.

### Expected Behavior

Bake should work and select the right UV.

### Addon Version

macOS (Apple Silicon)

### GPU

Apple Silicon

**Comment by enzyme69** [comment] 2023-03-07 01:18
Sorry to bring this one back, I think there is definitely a "bug" even with "Non Bake" setup. 

It should have selected "Projected UV" for 3D viewport to show the right one.
![Screenshot 2023-03-07 at 12 13 04 pm](https://user-images.githubusercontent.com/3952687/223293491-98df9a10-e450-45bc-a19e-f7841af99896.png)

I also tried the Ortographic and also ensuring the 3D viewport is as square as possible.
![Screenshot 2023-03-07 at 12 16 30 pm](https://user-images.githubusercontent.com/3952687/223293969-e114d980-c15c-4eaf-81c0-72b309acc2d7.png)

But the "Bake" option is something else. I will try making video...

**Comment by carson-katri** [comment] 2023-03-07 01:20
Closing as duplicate of #581 

If the issue is not resolved, please re-open that issue.

**Closed by carson-katri** 2023-03-07 01:20 UTC
Labels: bug

**Comment by enzyme69** [comment] 2023-03-07 01:22
Strange!!!! it's actually kind of working now. I must have gone crazy. 

Previously I had multiple meshes selected while doing "Bake".  And the result was totally messy.

I don't know if this works correctly now because: I already have "Projected UV" beforehand, and then select the correct original final UV.

![Screenshot 2023-03-07 at 12 20 29 pm](https://user-images.githubusercontent.com/3952687/223294519-624e9855-c2f5-4a98-90f4-f87faec9566f.png)
