### ISSUE TITLE
Sintax error

### ISSUE THREAD

**Issue by AlanJordanMartinez** [carson-katri/dream-textures#710] opened 2023-09-23 23:40 UTC
### Description

Hi ! i try to install the last update in my blender 3.4 but i have this issue when i try to intall.. how can i fix it? thanks!

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Alan\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\dream-textures-main\__init__.py", line 39, in <module>
    from .render_pass import register_render_pass, unregister_render_pass, pass_inputs
  File "C:\Users\Alan\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\dream-textures-main\render_pass.py", line 91
    match scene.dream_textures_render_properties_pass_inputs:
          ^
SyntaxError: invalid syntax

### Steps to Reproduce

Go to "Enable addon"
And when click on the box,, the issue appears

### Expected Behavior

i expected this work in my pc

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by NullSenseStudio** [comment] 2023-09-25 16:55
The error shows you're using Blender 3.0, not 3.4. At least 3.1 is required.

duplicate of #615

**Closed by NullSenseStudio** 2023-09-25 16:55 UTC
Labels: bug
