### ISSUE TITLE
An error occurred while generating. Check the issues tab on GitHub to see if this has been reported before:

### ISSUE THREAD

**Issue by adityapandeyz** [carson-katri/dream-textures#671] opened 2023-05-20 10:07 UTC
An error occurred while generating. Check the issues tab on GitHub to see if this has been reported before:

OSError('Error no file named diffusion_pytorch_model.bin found in directory C:\\Users\\adity\\.cache\\huggingface\\hub\\models--stabilityai--stable-diffusion-2-depth\\snapshots\\6330e936a1cc2da7fe149bfba83462003f5e71c7\\unet.')

**Comment by carson-katri** [comment] 2023-05-21 02:31
Duplicate of #622

**Closed** 2023-05-21 02:31 UTC

**Comment by shiyuze112** [comment] 2023-11-08 11:01
Hello, got it solved？
