### ISSUE TITLE
Cuda out of Memory

### ISSUE THREAD

**Issue by AaryamanCodes** [carson-katri/dream-textures#172] opened 2022-09-28 15:30 UTC
System Specifications:
Windows 11 Pro
Blender 3.3.0
GTX 1650 - 4 gb

When trying to generate textures, the following bug comes up.
`Error: RuntimeError('CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 4.00 GiB total capacity; 3.39 GiB already allocated; 0 bytes free; 3.44 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF')`

How to solve this? (Please note my GPU use is minimal with nothing else open)

**Comment by NullSenseStudio** [comment] 2022-09-28 15:49
Unfortunately GTX 1600 cards require full precision enabled to run and that makes it use more VRAM. How things currently work it's likely going to be impossible for you. Hopefully in a later release that may change.

**Comment by mattiabruni** [comment] 2022-09-28 15:57
If you want you can look at the addon to understand how to make a prompt and then follow a guide like this
https://bytexd.com/best-way-to-run-stable-diffusion-for-free/ 
to use SD on a cloud computer. It is definitely more involved though.

**Comment by AaryamanCodes** [comment] 2022-09-28 15:58
> Unfortunately GTX 1600 cards require full precision enabled to run and that makes it use more VRAM. How things currently work it's likely going to be impossible for you. Hopefully in a later release that may change.

Yeah, but like it isn't allowing me to use even two MB of ram.

**Comment by carson-katri** [comment] 2022-09-28 19:53
It had already used over 3GB of the 4 when trying to allocate more. Closing as this is not a bug but a hardware limitation.

**Closed by carson-katri** 2022-09-28 19:53 UTC
Labels: bug
