### ISSUE TITLE
Error when trying to modify any source image

### ISSUE THREAD

**Issue by HenrikoMagnifico** [carson-katri/dream-textures#467] opened 2022-12-21 18:45 UTC
### Description

Theis errror does not occur on version 0.0.8.
Trying to modify any source image results in this error;

`Read prefs: C:\Users\henri\AppData\Roaming\Blender Foundation\Blender\3.4\config\userpref.blend
Info: Total files 0 | Changed 0 | Failed 0
Info: Saved "stable diffusion 2-1 v2.blend"

Exception in thread Thread-2 (_send_thread):
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\henri\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actor.py", line 299, in _send_thread
    response = self._response_queue.get()
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\multiprocessing\queues.py", line 122, in get
    return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'torch'
Exception in thread Thread-3 (_send_thread):
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\henri\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actor.py", line 299, in _send_thread
    response = self._response_queue.get()
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\multiprocessing\queues.py", line 122, in get
    return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'torch'
Exception in thread Thread-4 (_send_thread):
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\henri\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actor.py", line 299, in _send_thread
    response = self._response_queue.get()
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\multiprocessing\queues.py", line 122, in get
    return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'torch'
`

### Steps to Reproduce

1. Use Blender 3.4.1 on Windows 11
2. Install dream-textures 0.0.9 as an addon, extract with 7-zip first and then add in the add-ons tab.
3. Download stable-diffusion 2-1 model using the built in GUI from the dream-textures addon.
4. Input any source image.
5. Try to modify, it will say "Starting..." forever and never progress. Resulting in an error in the console.

### Expected Behavior

For the add-on to process and render the new image successfully.

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by playerla** [comment] 2023-01-13 23:52
Hi, I find same bug (CUDA, same error stack). 
I have the same "steps to reproduce"

**Comment by carson-katri** [comment] 2023-01-15 13:50
Check Window > Toggle System Console for an error message.

**Comment by playerla** [comment] 2023-01-15 23:25
```
Read prefs: C:\Users\bjeub\AppData\Roaming\Blender Foundation\Blender\3.4\config\userpref.blend
Exception in thread Thread-2 (_send_thread):
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\bjeub\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actor.py", line 299, in _send_thread
    response = self._response_queue.get()
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\multiprocessing\queues.py", line 122, in get
    return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'torch'
```

**Comment by carson-katri** [comment] 2023-01-15 23:37
Typically this error means you ran out of VRAM: https://github.com/carson-katri/dream-textures/issues/505#issuecomment-1382603725
I’m going to close this as VRAM requirements are not a defect in the addon, and several other duplicates are open as well.

**Closed by carson-katri** 2023-01-15 23:37 UTC
Labels: bug

**Comment by playerla** [comment] 2023-01-16 00:02
Ok made some tests, it seems to be that
Thank you
