### ISSUE TITLE
<title>

### ISSUE THREAD

**Issue by wbj007007** [carson-katri/dream-textures#704] opened 2023-09-01 08:32 UTC
### Description

An error occurred while generating. Check the issues tab on GitHub to see if this has been reported before:

OSError('Error no file named diffusion_pytorch_model.bin found in directory C:\\Users\\DELL\\.cache\\huggingface\\hub\\models--lllyasviel--sd-controlnet-depth\\snapshots\\35e42a3ea49845b3c76f202f145f257b9fb1b7d4.')

### Steps to Reproduce

An error occurred while generating. Check the issues tab on GitHub to see if this has been reported before:

OSError('Error no file named diffusion_pytorch_model.bin found in directory C:\\Users\\DELL\\.cache\\huggingface\\hub\\models--lllyasviel--sd-controlnet-depth\\snapshots\\35e42a3ea49845b3c76f202f145f257b9fb1b7d4.')

### Expected Behavior

An error occurred while generating. Check the issues tab on GitHub to see if this has been reported before:

OSError('Error no file named diffusion_pytorch_model.bin found in directory C:\\Users\\DELL\\.cache\\huggingface\\hub\\models--lllyasviel--sd-controlnet-depth\\snapshots\\35e42a3ea49845b3c76f202f145f257b9fb1b7d4.')

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by carson-katri** [comment] 2023-09-09 02:35
Duplicate of #622

**Closed by carson-katri** 2023-09-09 02:35 UTC
Labels: bug
