### ISSUE TITLE
Nothing works now v 0.0.8 does not even work :(

### ISSUE THREAD

**Issue by enzyme69** [carson-katri/dream-textures#402] opened 2022-11-21 10:06 UTC
### Description

I don't know which latest version that's actually working on Mac M1.

I downloaded latet v 0.0.8 release and it won't work at all on Blender 3.5.

### Steps to Reproduce

Error message:
```
Info: Total files 0 | Changed 0 | Failed 0
Traceback (most recent call last):
  File "/Users/blendersushi/Library/Application Support/Blender/3.5/scripts/addons/dream_textures/generator_process/__init__.py", line 326, in main
    back.main_loop()
  File "/Users/blendersushi/Library/Application Support/Blender/3.5/scripts/addons/dream_textures/generator_process/__init__.py", line 269, in main_loop
    intents[intent].send(args)
  File "/Users/blendersushi/Library/Application Support/Blender/3.5/scripts/addons/dream_textures/generator_process/intents/prompt_to_image.py", line 194, in prompt_to_image
    generator.prompt2image(
  File "/Users/blendersushi/Library/Application Support/Blender/3.5/scripts/addons/dream_textures/stable_diffusion/ldm/generate.py", line 348, in prompt2image
    configure_model_padding(model, seamless, seamless_axes)
  File "/Users/blendersushi/Library/Application Support/Blender/3.5/scripts/addons/dream_textures/stable_diffusion/ldm/invoke/seamless.py", line 15, in configure_model_padding
    for m in model.modules():
AttributeError: 'NoneType' object has no attribute 'modules'

Error: AttributeError("'NoneType' object has no attribute 'modules'")
```

### Expected Behavior

We should have at least 1 working release.

### Addon Version

macOS (Apple Silicon)

### GPU

Apple Silicon

**Comment by carson-katri** [comment] 2022-11-21 13:26
This is a duplicate of #388

**Comment by carson-katri** [comment] 2022-11-21 13:26
Please try doing this and getting the full log: https://github.com/carson-katri/dream-textures/issues/388#issuecomment-1304809245

**Closed by carson-katri** 2022-11-21 13:26 UTC
Labels: bug
