### ISSUE TITLE
multiviewprojection

### ISSUE THREAD

**Issue by ekswathi** [carson-katri/dream-textures#613] opened 2023-03-25 06:53 UTC
I am pretty sure you are aware of this addon - SDTG4B(in development)
It is doing well with projecting images from different cameras. and making saving to single uvmap.
I am just trying to be helpful.
thank you for your fantastic addon
the link is given below.
https://github.com/p4vv37/SDTG4B

**Comment by carson-katri** [comment] 2023-03-25 17:31
Duplicate of #446

**Closed by carson-katri** 2023-03-25 17:31 UTC
Labels: enhancement
