### ISSUE TITLE
Error installing dependencies on windows

### ISSUE THREAD

**Issue by HowTheHellDoIdoThis** [carson-katri/dream-textures#13] opened 2022-09-18 01:39 UTC
I've tried 4 different times to install, ive reinstalled both blender and the addon and each time it gets a decent way through before getting stuck
The blender info log says this:

`Command '['C:\\Program Files\\Blender Foundation\\Blender 3.3\\3.3\\python\\bin\\python.EXE', '-m', 'pip', 'install', '-r', 'C:\\Users\\Mason\\AppData\\Roaming\\Blender Foundation\\Blender\\3.3\\scripts\\addons\\dream_textures\\requirements-win-torch-1-11-0.txt', '--no-cache-dir']' returned non-zero exit status 1.`

And the python command prompt looking thing tells me this:

`ERROR: Could not find a version that satisfies the requirement basicsr>=1.4.2 (from gfpgan) (from versions: 1.3.1, 1.3.2, 1.3.3, 1.3.3.1, 1.3.3.3, 1.3.3.4, 1.3.3.5, 1.3.3.6, 1.3.3.7, 1.3.3.8, 1.3.3.9, 1.3.3.10, 1.3.3.11, 1.3.4.0, 1.3.4.1, 1.3.4.2, 1.3.4.3, 1.3.4.4, 1.3.4.6, 1.3.4.7, 1.3.4.8, 1.3.4.9, 1.3.5, 1.4.0, 1.4.1, 1.4.2)
ERROR: No matching distribution found for basicsr>=1.4.2
WARNING: You are using pip version 21.2.4; however, version 22.2.2 is available.
You should consider upgrading via the 'C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\bin\python.EXE -m pip install --upgrade pip' command.
`

help please

edit: im trying to upgrade pip through python like its telling me but i have absolutely no frame of reference whatsoever for how to use python

edit: GPU is a gtx 1660, also realized it might not be a good idea trying to mess with python

**Comment by gregnr** [comment] 2022-09-18 03:32
@HowTheHellDoIdoThis I've found a fix for this described in this PR: #15. This worked for me, I hope it does for you as well. Let me know if it works!

**Comment by HowTheHellDoIdoThis** [comment] 2022-09-18 04:10
Thank you so much, it doesnt get stuck anymore, but now when I try and generate anything it says there is no current event loop

**Comment by gregnr** [comment] 2022-09-18 04:44
Glad that worked! I never did encounter that one, but you could follow this existing issue to see if anybody else finds a solution: #9

**Closed** 2022-09-18 04:45 UTC

**Comment by chrisvian** [comment] 2022-09-21 17:07
Hi help, the blender info log always popping this message whenever i tried to install dependencies

> ERROR: file:///C:/Users/CHRIS/AppData/Roaming/Blender%20Foundation/Blender/3.3/scripts/addons/dream-textures-main/stable_diffusion (from -r C:\Users\CHRIS\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream-textures-main\requirements-win-torch-1-11-0.txt (line 33)) does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

**Comment by carson-katri** [comment] 2022-09-21 17:09
@chrisvian Looks like you downloaded the source code not the packaged addon. Please download the file `dream_textures.zip` from the releases tab: https://github.com/carson-katri/dream-textures/releases/tag/0.0.5

**Comment by chrisvian** [comment] 2022-09-21 17:45
> @chrisvian Looks like you downloaded the source code not the packaged addon. Please download the file `dream_textures.zip` from the releases tab: https://github.com/carson-katri/dream-textures/releases/tag/0.0.5

Thank you! It's working!

**Comment by AndrewDGonzalez** [comment] 2022-09-21 19:50
Hello! I'm having an issue as well with the dependencies. 

**ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: C:\Users\Andrew PC\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream-textures-main\stable_diffusion
WARNING: You are using pip version 21.2.4; however, version 22.2.2 is available.
You should consider upgrading via the 'C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\bin\python.EXE -m pip install --upgrade pip' command.**

This is what I get from the terminal as soon as it starts the installation. I tried the previous LongRun fix but that didn't change anything here. I've reinstalled both Dreams and Blender a few times now to reset directories but also to no avail.

**Comment by carson-katri** [comment] 2022-09-21 19:52
@AndrewDGonzalez you downloaded the wrong file. You need to download the `dream_textures.zip` file from the releases tab, not the source code. See #47

**Comment by AndrewDGonzalez** [comment] 2022-09-21 19:57
Oh wow! You're fast. And yeah, I guess that's what happened. I just clicked the Code - download ZIP button and thought that was the program. Thank you ver much!

**Comment by JagmasterPHD** [comment] 2022-09-23 16:41
Hi, I'm getting this error installing the dependencies:  PermissionError: [WinError 5] Access is denied: 'C:\\Program Files\\WindowsApps\\BlenderFoundation.Blender_3.3.0.0_x64__ppwjx1n5r4v9t\\Blender\\3.3\\python\\Include'

**Comment by GrandGeneralHaas** [comment] 2022-09-23 22:22
ERROR: Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/openai/CLIP.git 'C:\Users\kelso\AppData\Local\Temp\pip-install-_sw3m1to\clip_de16f88287b24f70b64e09ee2f647b52'
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
WARNING: You are using pip version 21.2.4; however, version 22.2.2 is available.
You should consider upgrading via the 'C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\bin\python.EXE -m pip install --upgrade pip' command.


Have already tried every other solution I have found.

**Comment by danielkisov** [comment] 2022-09-23 22:22
I am getting the same 
`PermissionError: [WinError 5] Access is denied: 'C:\\Program Files\\WindowsApps\\BlenderFoundation.Blender_3.3.0.0_x64__ppwjx1n5r4v9t\\Blender\\3.3\\python\\Include'` 
error (and, yes, I have started blender as administrator)

**Comment by 00LukeSkyworker00** [comment] 2022-09-24 03:40
> Hi, I'm getting this error installing the dependencies: PermissionError: [WinError 5] Access is denied: 'C:\Program Files\WindowsApps\BlenderFoundation.Blender_3.3.0.0_x64__ppwjx1n5r4v9t\Blender\3.3\python\Include'

I solve this by running blender as administrator. Hope this fix your problem.

**Comment by 00LukeSkyworker00** [comment] 2022-09-24 03:41
> ERROR: Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/openai/CLIP.git 'C:\Users\kelso\AppData\Local\Temp\pip-install-_sw3m1to\clip_de16f88287b24f70b64e09ee2f647b52' ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH? WARNING: You are using pip version 21.2.4; however, version 22.2.2 is available. You should consider upgrading via the 'C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\bin\python.EXE -m pip install --upgrade pip' command.
> 
> Have already tried every other solution I have found.

I solve this by running blender as administrator. Hope this fix your problem.

**Comment by igdeputra** [comment] 2022-09-24 08:32
> dministrator)

same

**Comment by igdeputra** [comment] 2022-09-24 08:35
> I am getting the same `PermissionError: [WinError 5] Access is denied: 'C:\\Program Files\\WindowsApps\\BlenderFoundation.Blender_3.3.0.0_x64__ppwjx1n5r4v9t\\Blender\\3.3\\python\\Include'` error (and, yes, I have started blender as administrator)

i work. just run blender as administrator. find blender exe in C:\Program Files\Blender Foundation\Blender 3.3

**Comment by AgainsTurb** [comment] 2022-09-24 08:38
When I try to install windows dependencies it shows this:
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:997)
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.python.org', port=443): Max retries exceeded with url: /ftp/python/3.10.2/Python-3.10.2.tgz (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
How can I fix it?

**Comment by philiphendry** [comment] 2022-09-24 12:30
I had a permission denied when install the dependencies and I'd run it as administrator. However, I'd installed Blender from the Windows Store so the path that was denied started "C:\\Program Files\\WindowsApps\\". So instead I download the installer from blender.org and used that instead.

**Comment by BeauCotter** [comment] 2022-09-24 13:02
Hello, I'm also having an issue installing the dependencies, when I try, blender puts out this error:

Python: Traceback (most recent call last):
  File "C:\Users\heyco\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\operators\install_dependencies.py", line 140, in execute
    install_pip()
  File "C:\Users\heyco\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\operators\install_dependencies.py", line 55, in install_pip
    subprocess.run([sys.executable, "-m", "pip", "--version"], check=True)
  File "E:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "E:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "E:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\subprocess.py", line 1375, in _execute_child
    args = list2cmdline(args)
  File "E:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\subprocess.py", line 561, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "E:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\os.py", line 822, in fsdecode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType

I've tried everything I could find...
Also, I don't know anything about python...
Any help appreciated :D

**Comment by Mungula** [comment] 2022-09-25 15:52
So far I have done everthing correctly but when I go to generate a texture nothing happens. I'm pretty sure it has something to do with this error:

Error: No module named 'antlr4'

Not sure how to fix this.

**Comment by Frank1345** [comment] 2022-09-25 19:25
how i can fix this error?
ERROR: Could not find a version that satisfies the requirement basicsr>=1.4.2 (from gfpgan) (from versions: 1.3.1, 1.3.2, 1.3.3, 1.3.3.1, 1.3.3.3, 1.3.3.4, 1.3.3.5, 1.3.3.6, 1.3.3.7, 1.3.3.8, 1.3.3.9, 1.3.3.10, 1.3.3.11, 1.3.4.0, 1.3.4.1, 1.3.4.2, 1.3.4.3, 1.3.4.4, 1.3.4.6, 1.3.4.7, 1.3.4.8, 1.3.4.9, 1.3.5, 1.4.0, 1.4.1, 1.4.2)
ERROR: No matching distribution found for basicsr>=1.4.2
WARNING: You are using pip version 21.2.4; however, version 22.2.2 is available.
You should consider upgrading via the 'C:\Program Files\Blender Foundation\Blender 3.1\3.1\python\bin\python.EXE -m pip install --upgrade pip' command.

**Comment by carson-katri** [comment] 2022-09-25 19:26
@Frank1345 See #23
