### ISSUE TITLE
Add ability to change directory where models are stored (e.g. use a drive other than C)

### ISSUE THREAD

**Issue by Zyberetro** [carson-katri/dream-textures#676] opened 2023-05-26 20:34 UTC
My C drive doesn't have much room on it, but I have two other drives, E and F that have plenty of room on them, unless there's something I'm missing, I have to use my C drive, even though I'd rather have my models stored on a different drive other than C.

**Comment by carson-katri** [comment] 2023-05-26 20:35
Duplicate of #534

**Closed by carson-katri** 2023-05-26 20:35 UTC
Labels: enhancement
