### ISSUE TITLE
Can't install the depenencies, I get this Errors but I have installed the pip 22.2.2  

### ISSUE THREAD

**Issue by JC-Sutter** [carson-katri/dream-textures#122] opened 2022-09-25 06:13 UTC
Can't install the depenencies, I get this Errors but I have installed the pip 22.2.2  

------------------------
ERROR: Command errored out with exit status 1:
     command: 'C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\bin\python.EXE' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-j6my9b1q\\basicsr_f71c4f1add8c4fb68883b1a76cdcf440\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-j6my9b1q\\basicsr_f71c4f1add8c4fb68883b1a76cdcf440\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\User\AppData\Local\Temp\pip-pip-egg-info-_9ligcez'
         cwd: C:\Users\User\AppData\Local\Temp\pip-install-j6my9b1q\basicsr_f71c4f1add8c4fb68883b1a76cdcf440\
    Complete output (32 lines):
    WARNING: The wheel package is not available.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\User\AppData\Local\Temp\pip-install-j6my9b1q\basicsr_f71c4f1add8c4fb68883b1a76cdcf440\setup.py", line 147, in <module>
        setup(
      File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\setuptools\__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\setuptools\__init__.py", line 147, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\setuptools\dist.py", line 806, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\pkg_resources\__init__.py", line 766, in resolve
        dist = best[req.key] = env.best_match(
      File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\pkg_resources\__init__.py", line 1051, in best_match
        return self.obtain(req, installer)
      File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\pkg_resources\__init__.py", line 1063, in obtain
        return installer(requirement)
      File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\setuptools\dist.py", line 877, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\setuptools\installer.py", line 80, in fetch_build_egg
        wheel.install_as_egg(dist_location)
      File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\setuptools\wheel.py", line 95, in install_as_egg
        self._install_as_egg(destination_eggdir, zf)
      File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\setuptools\wheel.py", line 103, in _install_as_egg
        self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
      File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\setuptools\wheel.py", line 125, in _convert_metadata
        zf.extractall(destination_eggdir)
      File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\zipfile.py", line 1634, in extractall
        self._extract_member(zipinfo, path, pwd)
      File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\zipfile.py", line 1688, in _extract_member
        open(targetpath, "wb") as target:
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-j6my9b1q\\basicsr_f71c4f1add8c4fb68883b1a76cdcf440\\.eggs\\torch-1.12.1-py3.10-win-amd64.egg\\caffe2\\python\\serialized_test\\data\\operator_test\\learning_rate_adaption_op_test.test_learning_rate_adaption_op_normalization.zip'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/86/41/00a6b000f222f0fa4c6d9e1d6dcc9811a374cabb8abb9d408b77de39648c/basicsr-1.4.2.tar.gz#sha256=b89b595a87ef964cda9913b4d99380ddb6554c965577c0c10cb7b78e31301e87 (from https://pypi.org/simple/basicsr/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

ERROR: Could not find a version that satisfies the requirement basicsr>=1.4.2 (from gfpgan) (from versions: 1.3.1, 1.3.2, 1.3.3, 1.3.3.1, 1.3.3.3, 1.3.3.4, 1.3.3.5, 1.3.3.6, 1.3.3.7, 1.3.3.8, 1.3.3.9, 1.3.3.10, 1.3.3.11, 1.3.4.0, 1.3.4.1, 1.3.4.2, 1.3.4.3, 1.3.4.4, 1.3.4.6, 1.3.4.7, 1.3.4.8, 1.3.4.9, 1.3.5, 1.4.0, 1.4.1, 1.4.2)
ERROR: No matching distribution found for basicsr>=1.4.2
WARNING: You are using pip version 21.2.4; however, version 22.2.2 is available.
You should consider upgrading via the 'C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\bin\python.EXE -m pip install --upgrade pip' command.

**Comment by carson-katri** [comment] 2022-09-25 11:45
Closing as a duplicate of #23

**Closed by carson-katri** 2022-09-25 11:45 UTC
