### ISSUE TITLE
ModuleNotFoundError: No module named 'dream_textures.prompt_engineering'

### ISSUE THREAD

**Issue by Dyo-Anima** [carson-katri/dream-textures#650] opened 2023-04-26 00:54 UTC
### Description

hello, I love your project but I have been unable to start it in blender 3.4 and 3.5, when I activate the addon I get this error.
I hope you can tell me the cause and a solution.
Best regards

![imagen](https://user-images.githubusercontent.com/117344759/234437946-1f6b484d-1029-40c2-9d69-dc9d658da5bb.png)

```
Traceback (most recent call last):
  File "F:\Programas\blender-3.5.0-windows-x64\3.5\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\nya\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\dream_textures\__init__.py", line 40, in <module>
    from .prompt_engineering import *
ModuleNotFoundError: No module named 'dream_textures.prompt_engineering'
```

### Steps to Reproduce

when activating the addon after installing the zip. it is the latest version of this release 0.2.0

### Expected Behavior

start correctly

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by carson-katri** [comment] 2023-04-26 00:56
Duplicate of #464

**Closed by carson-katri** 2023-04-26 00:56 UTC
Labels: bug
