### ISSUE TITLE
Error installing dependences (file not found)

### ISSUE THREAD

**Issue by supertpbs** [carson-katri/dream-textures#87] opened 2022-09-23 15:03 UTC
ERROR: file:///C:/Users/super/AppData/Roaming/Blender%20Foundation/Blender/3.3/scripts/addons/dream-textures-main/stable_diffusion (from -r C:\Users\super\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream-textures-main\requirements-win-torch-1-11-0.txt (line 33)) does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

**Comment by detapa** [comment] 2022-09-23 15:33
Similar problem here, could this be caused by the lack of Nvidia CUDA? 

pytorch.org recommends another method of installation for non CUDA systems..

![image](https://user-images.githubusercontent.com/352900/191998146-78bfe90d-ee40-4c2a-9f53-f2d6c2add079.png)

**Comment by yu0bab** [comment] 2022-09-23 18:07
To detapa, I have Nvidia CUDA and I'm getting the same error
I'm new to Github so if this message goes to the wrong person, please tell me

**Comment by detapa** [comment] 2022-09-23 18:23
> To detapa, I have Nvidia CUDA and I'm getting the same error I'm new to Github so if this message goes to the wrong person, please tell me

Hey, the msg reached me... problem is still though...

**Comment by yu0bab** [comment] 2022-09-23 18:25
So there's no known solution yet?

**Comment by carson-katri** [comment] 2022-09-23 18:25
@supertpbs you just downloaded the wrong file. You need to download the one called `dream_textures.zip` in the releases tab. Closing this as a duplicate of #47

**Closed by carson-katri** 2022-09-23 18:25 UTC
