### ISSUE TITLE
When trying to generate a texture, I get an error about the lack of video memory.

### ISSUE THREAD

**Issue by SculptorGoldenMoon** [carson-katri/dream-textures#573] opened 2023-02-19 09:03 UTC
### Description

When trying to generate a texture, I get an error about the lack of video memory.
'
An error occurred while generating. Check the issues tab on GitHub to see if this has been reported before:

RuntimeError("OutOfMemoryError('CUDA out of memory. Tried to allocate 648.00 MiB (GPU 0; 4.00 GiB total capacity; 3.16 GiB already allocated; 0 bytes free; 3.20 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF')")
'
Video adapter: nVIDIA GeForce GTX 1050 Ti

The error occurs because of not enough video memory on my video card?
I'm using version 0.1.0 of Dreamy Textures.

### Steps to Reproduce

1. Installed addon "Dreamy textures" in Blender.
2. Installed the "stability/stable-diffusion-2-1" module at the request of the system.
3. Tried to generate texture and error.

### Expected Behavior

Waiting for texture generation

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by RazorWolvendom** [comment] 2023-02-19 18:24
did you tried to generate at a different resolution?

**Comment by sorecords** [comment] 2023-02-21 11:59
Get the same issue with MSI RTX2080ti 12 Gb, when trying to generate 1024x1024 textures with Dream Textures v 0.1.0 in Blender 3.4.1. It worked fine with even higher resolutions at least in 0.0.8. The exception traceback is following:

>   0%|                                                                                           | 0/25 [00:01<?, ?it/s]
> Exception: Traceback (most recent call last):
>   File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actor.py", line 273, in _receive
>     for res in iter(response):
>   File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actions\prompt_to_image.py", line 565, in prompt_to_image
>     yield from pipe(
>   File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\torch\autograd\grad_mode.py", line 43, in generator_context
>     response = gen.send(None)
>   File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actions\prompt_to_image.py", line 508, in __call__
>     noise_pred = self.unet(latent_model_input, t, encoder_hidden_states=text_embeddings).sample
>   File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\torch\nn\modules\module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\diffusers\models\unet_2d_condition.py", line 580, in forward
>     sample, res_samples = downsample_block(
>   File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\torch\nn\modules\module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\diffusers\models\unet_2d_blocks.py", line 837, in forward
>     hidden_states = attn(
>   File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\torch\nn\modules\module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\diffusers\models\transformer_2d.py", line 265, in forward
>     hidden_states = block(
>   File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\torch\nn\modules\module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\diffusers\models\attention.py", line 291, in forward
>     attn_output = self.attn1(
>   File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\torch\nn\modules\module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\diffusers\models\cross_attention.py", line 202, in forward
>     return self.processor(
>   File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\diffusers\models\cross_attention.py", line 546, in __call__
>     attn_slice = attn.get_attention_scores(query_slice, key_slice, attn_mask_slice)
>   File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\diffusers\models\cross_attention.py", line 251, in get_attention_scores
>     attention_probs = attention_probs.to(dtype)
> torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 11.00 GiB total capacity; 8.61 GiB already allocated; 0 bytes free; 9.67 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> 
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actor.py", line 98, in run_callbacks
>     exception_callback(self, exception)
>   File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\operators\dream_texture.py", line 156, in exception_callback
>     raise exception
> RuntimeError: OutOfMemoryError('CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 11.00 GiB total capacity; 8.61 GiB already allocated; 0 bytes free; 9.67 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF')
> 
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actor.py", line 98, in run_callbacks
>     exception_callback(self, exception)
>   File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\operators\dream_texture.py", line 156, in exception_callback
>     raise exception
> RuntimeError: OutOfMemoryError('CUDA out of memory. Tried to allocate 2.00 GiB (GPU 0; 11.00 GiB total capacity; 6.76 GiB already allocated; 311.00 MiB free; 8.77 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF')

**Comment by SculptorGoldenMoon** [comment] 2023-02-22 20:02
> did you tried to generate at a smaller resolution?

Okay, 512 pixels is the maximum for it. In any case, there is not enough memory for large resolutions.
Or can I still use "max_split_size_mb" to decrease the maximum value and generate a larger image ?

**Comment by SculptorGoldenMoon** [comment] 2023-02-22 20:05
> Get the same issue with MSI RTX2080ti 12 Gb, when trying to generate 1024x1024 textures with Dream Textures v 0.1.0 in Blender 3.4.1. It worked fine with even higher resolutions at least in 0.0.8. The exception traceback is following:

Okay, 512 pixels is the maximum for it. In any case, there is not enough memory for large resolutions.
Or can I still use "max_split_size_mb" to decrease the maximum value and generate a larger image ?

**Comment by RazorWolvendom** [comment] 2023-02-22 23:18
> Get the same issue with MSI RTX2080ti 12 Gb, when trying to generate 1024x1024 textures with Dream Textures v 0.1.0 in Blender 3.4.1. It worked fine with even higher resolutions at least in 0.0.8. The exception traceback is following:
> 
> > 0%|                                                                                           | 0/25 [00:01<?, ?it/s]
> > Exception: Traceback (most recent call last):
> > File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actor.py", line 273, in _receive
> > for res in iter(response):
> > File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actions\prompt_to_image.py", line 565, in prompt_to_image
> > yield from pipe(
> > File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures.python_dependencies\torch\autograd\grad_mode.py", line 43, in generator_context
> > response = gen.send(None)
> > File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actions\prompt_to_image.py", line 508, in **call**
> > noise_pred = self.unet(latent_model_input, t, encoder_hidden_states=text_embeddings).sample
> > File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures.python_dependencies\torch\nn\modules\module.py", line 1194, in _call_impl
> > return forward_call(*input, **kwargs)
> > File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures.python_dependencies\diffusers\models\unet_2d_condition.py", line 580, in forward
> > sample, res_samples = downsample_block(
> > File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures.python_dependencies\torch\nn\modules\module.py", line 1194, in _call_impl
> > return forward_call(*input, **kwargs)
> > File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures.python_dependencies\diffusers\models\unet_2d_blocks.py", line 837, in forward
> > hidden_states = attn(
> > File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures.python_dependencies\torch\nn\modules\module.py", line 1194, in _call_impl
> > return forward_call(*input, **kwargs)
> > File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures.python_dependencies\diffusers\models\transformer_2d.py", line 265, in forward
> > hidden_states = block(
> > File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures.python_dependencies\torch\nn\modules\module.py", line 1194, in _call_impl
> > return forward_call(*input, **kwargs)
> > File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures.python_dependencies\diffusers\models\attention.py", line 291, in forward
> > attn_output = self.attn1(
> > File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures.python_dependencies\torch\nn\modules\module.py", line 1194, in _call_impl
> > return forward_call(*input, **kwargs)
> > File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures.python_dependencies\diffusers\models\cross_attention.py", line 202, in forward
> > return self.processor(
> > File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures.python_dependencies\diffusers\models\cross_attention.py", line 546, in **call**
> > attn_slice = attn.get_attention_scores(query_slice, key_slice, attn_mask_slice)
> > File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures.python_dependencies\diffusers\models\cross_attention.py", line 251, in get_attention_scores
> > attention_probs = attention_probs.to(dtype)
> > torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 11.00 GiB total capacity; 8.61 GiB already allocated; 0 bytes free; 9.67 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> > The above exception was the direct cause of the following exception:
> > Traceback (most recent call last):
> > File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actor.py", line 98, in run_callbacks
> > exception_callback(self, exception)
> > File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\operators\dream_texture.py", line 156, in exception_callback
> > raise exception
> > RuntimeError: OutOfMemoryError('CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 11.00 GiB total capacity; 8.61 GiB already allocated; 0 bytes free; 9.67 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF')
> > The above exception was the direct cause of the following exception:
> > Traceback (most recent call last):
> > File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actor.py", line 98, in run_callbacks
> > exception_callback(self, exception)
> > File "C:\Users\1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\operators\dream_texture.py", line 156, in exception_callback
> > raise exception
> > RuntimeError: OutOfMemoryError('CUDA out of memory. Tried to allocate 2.00 GiB (GPU 0; 11.00 GiB total capacity; 6.76 GiB already allocated; 311.00 MiB free; 8.77 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF')

funny actually same, i also was able to generate something like up to 946x946 in earlier versions and now just 872x872 or something

**Comment by SculptorGoldenMoon** [comment] 2023-02-23 12:52
Sorry, should I install version 0.0.8 ?

**Comment by carson-katri** [comment] 2023-02-23 13:14
Closing this as it is not a bug in Dream Textures, but a hardware limitation.

**Closed by carson-katri** 2023-02-23 13:14 UTC
Labels: bug

**Comment by sorecords** [comment] 2023-02-23 13:53
Sorry, I surely can not insist, just want to mention that in the previous versions add-on handles twice resolution comparing to 0.1.0 with the same hardware.

**Comment by carson-katri** [comment] 2023-02-23 13:58
@sorecords v0.1.0 gives finer grained control over optimizations, so you may need to tweak more settings. For example, setting the attention slice size to 1 will reduce VRAM usage while sacrificing some speed.

#575 will add more optimization options as well.

**Comment by MrNishu07** [comment] 2023-09-24 04:57
I am facing the same error, can anyone help me?
An error occurred while generating. Check the issues tab on GitHub to see if this has been reported before:

RuntimeError("OutOfMemoryError('CUDA out of memory. Tried to allocate 58.00 MiB (GPU 0; 4.00 GiB total capacity; 3.39 GiB already allocated; 0 bytes free; 3.44 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF')")

**Comment by RazorWolvendom** [comment] 2023-09-24 16:27
> I am facing the same error, can anyone help me? An error occurred while generating. Check the issues tab on GitHub to see if this has been reported before:
> 
> RuntimeError("OutOfMemoryError('CUDA out of memory. Tried to allocate 58.00 MiB (GPU 0; 4.00 GiB total capacity; 3.39 GiB already allocated; 0 bytes free; 3.44 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF')")

use a smaller resolution to generate
